/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proy_integ_4la;

import ORCLCONEXION.ConectarAOracle;
import java.util.Date;                  // para java.util.Date que devuelve JDateChooser
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import utiles.EquiposSeleccionados;
import utiles.SalasSeleccionada;
import utiles.SesionUsuario;

public class EquipoReservado extends javax.swing.JFrame {
private final ConectarAOracle gestor = new ConectarAOracle();
    private final Connection conexion = gestor.abrir();
    /**
     * Creates new form EquipoReservado
     */
    public EquipoReservado() {
        initComponents();
         nombreequipo.setText(EquiposSeleccionados.nombre );
        estadoequipo.setText( EquiposSeleccionados.estado );
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estadoequipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreequipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fechainicio = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        fechafin = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setText("Estado");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Equipo Reservado");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel2.setText("Nombre");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        jLayeredPane1.add(nombreequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, -1));

        jLabel4.setText("Fecha Inicio");
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
        jLayeredPane1.add(fechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 130, -1));

        jLabel5.setText("Fecha Fin");
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));
        jLayeredPane1.add(fechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 130, -1));

        jButton1.setText("Rerservar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jButton2.setText("volver");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/FondoEstandar.png"))); // NOI18N
        jLayeredPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
 try {
    // Obtener fechas como java.util.Date
    Date fechaInicioUtil = fechainicio.getDate();
    Date fechaFinUtil = fechafin.getDate();

    // Validar fechas
    if (fechaInicioUtil == null || fechaFinUtil == null) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona ambas fechas.");
        return;
    }

    if (!fechaInicioUtil.before(fechaFinUtil)) {
        JOptionPane.showMessageDialog(this, "La fecha de inicio debe ser menor que la fecha fin.");
        return;
    }

    // Convertir a java.sql.Date
    java.sql.Date fechaInicioSQL = new java.sql.Date(fechaInicioUtil.getTime());
    java.sql.Date fechaFinSQL = new java.sql.Date(fechaFinUtil.getTime());

    // Preparar e insertar en Oracle
    String sql = "INSERT INTO prestamos (id_préstamo, id_usuario, fecha_inicio, fecha_fin, estado, id_equipo) " +
                 "VALUES (seq_prestamos.NEXTVAL, ?, ?, ? , 'en espera', ?)";

    try {
        PreparedStatement ps = conexion.prepareStatement(sql);
        ps.setInt(1, SesionUsuario.idUsuario);  // ID_USUARIO desde sesión
        ps.setDate(2, fechaInicioSQL);          // FECHA_INICIO
        ps.setDate(3, fechaFinSQL);             // FECHA_FIN               
        ps.setObject(4, EquiposSeleccionados.id);                // ID_SALA (puede ser null)

        int filas = ps.executeUpdate();

        if (filas > 0) {
            JOptionPane.showMessageDialog(this, "Préstamo guardado correctamente.");
        }

        ps.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos:\n" + e.getMessage());
        e.printStackTrace();
    }

} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Error general:\n" + ex.getMessage());
    ex.printStackTrace();
}
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
            ReservarEquipos cr=new ReservarEquipos();
             cr.setVisible(true);
             dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquipoReservado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquipoReservado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquipoReservado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquipoReservado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EquipoReservado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField estadoequipo;
    private com.toedter.calendar.JDateChooser fechafin;
    private com.toedter.calendar.JDateChooser fechainicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField nombreequipo;
    // End of variables declaration//GEN-END:variables
}
